/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAlert: typeof import('./src/components/app/AppAlert.vue')['default']
    AppCard: typeof import('./src/components/app/AppCard.vue')['default']
    AppGrid: typeof import('./src/components/app/AppGrid.vue')['default']
    AppLoadingSpinner: typeof import('./src/components/app/AppLoadingSpinner.vue')['default']
    AppModal: typeof import('./src/components/app/AppModal.vue')['default']
    AppPagination: typeof import('./src/components/app/AppPagination.vue')['default']
    LoadingSpinner: typeof import('./src/components/app/LoadingSpinner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
